[package]
name = "windex"
version = "0.1.0"
authors = ["Brighton Sikarskie <brighton.sikarskie@tuta.io>"]
edition = "2018"

[dependencies]
x11 = { version = "2.18.2", features = ["xlib", "xlib_xcb"] }
